# Generated by Django 3.2 on 2022-01-18 12:33

from django.db import migrations, models
import utils.functions
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.functions.PathAndRename('uploads/images'), validators=[utils.validators.validate_image_size], verbose_name='썸네일'),
        ),
    ]
