# Generated by Django 3.2 on 2022-01-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_content_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_num', models.BigAutoField(db_index=True, help_text='Post Number', primary_key=True, serialize=False)),
                ('unq_id', models.CharField(max_length=266, verbose_name='이메일')),
                ('shoe_brand', models.CharField(max_length=256, verbose_name='브랜드')),
                ('shoe_name', models.CharField(max_length=256, verbose_name='신발명')),
                ('shoe_size', models.IntegerField(verbose_name='사이즈')),
                ('shoe_color', models.CharField(max_length=256, verbose_name='색깔')),
            ],
            options={
                'verbose_name': '컨텐츠',
                'verbose_name_plural': '컨텐츠(들)',
            },
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
