# Generated by Django 3.2 on 2022-01-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20220119_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_num',
            field=models.IntegerField(db_index=True, help_text='Post Number', primary_key=True, serialize=False),
        ),
    ]
