# Generated by Django 3.2 on 2022-01-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.CharField(max_length=256, verbose_name='sub')),
                ('shoe_id', models.CharField(max_length=256, verbose_name='브랜드12')),
                ('shoe_name', models.CharField(max_length=256, verbose_name='신발명')),
                ('shoe_brand', models.CharField(max_length=256, verbose_name='브랜드')),
                ('shoe_size', models.CharField(max_length=256, verbose_name='사이즈')),
                ('shoe_color', models.CharField(max_length=256, verbose_name='색깔')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shoe_images')),
            ],
        ),
    ]
