# Generated by Django 3.2 on 2022-01-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_name', models.CharField(max_length=256, verbose_name='신발명')),
                ('shoe_brand', models.CharField(max_length=256, verbose_name='브랜드')),
                ('shoe_size', models.CharField(max_length=256, verbose_name='사이즈')),
                ('shoe_color', models.CharField(max_length=256, verbose_name='색깔')),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
