# Generated by Django 3.2 on 2022-01-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0002_auto_20220124_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='shoe_brand',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='브랜드'),
        ),
        migrations.AlterField(
            model_name='test1',
            name='shoe_color',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='색깔'),
        ),
        migrations.AlterField(
            model_name='test1',
            name='shoe_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='신발명'),
        ),
        migrations.AlterField(
            model_name='test1',
            name='shoe_size',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='사이즈'),
        ),
    ]
