import Head from "next/head";
import Header from "../src/components/header/index";
import Footer from "../src/components/footer/index";

export default function Home() {
  return (
    <main className="main">
      <Head>
        <title>ShoeFinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <iframe
        src="https://giphy.com/embed/f6zPlLMBdrqvEpZ78a"
        width="480"
        height="347"
        frameBorder="0"
        className="w-full giphy-embed"
        allowFullScreen
      ></iframe>
      <Footer />
    </main>
  );
}
